##########################################################################################################################
# Enhanced Makefile for STM32 all family support
##########################################################################################################################

TARGET = final
DEBUG = 1
OPT = -Og
BUILD_DIR = Output

#######################################
# Select MCU Family (default = F4)
#######################################
MCU_FAMILY ?= F4

ifeq ($(MCU_FAMILY),F4)
CPU         = -mcpu=cortex-m4
FPU         = -mfpu=fpv4-sp-d16
FLOAT_ABI   = -mfloat-abi=hard
C_DEFS      = -DUSE_HAL_DRIVER -DSTM32F446xx
LDSCRIPT    = HAL/ST/stm32f4/STM32F4xx_HAL_Driver/stm32f4_flash.ld
ASM_SOURCES = HAL/ST/stm32f4/STM32F4xx_HAL_Driver/startup_stm32f4.s
endif


ifeq ($(MCU_FAMILY),F7)
CPU         = -mcpu=cortex-m7
FPU         = -mfpu=fpv5-sp-d16
FLOAT_ABI   = -mfloat-abi=hard
C_DEFS      = -DUSE_HAL_DRIVER -DSTM32F767xx
LDSCRIPT    = stm32f767zi_flash.ld
ASM_SOURCES = startup_stm32f767xx.s
endif

ifeq ($(MCU_FAMILY),H7)
CPU         = -mcpu=cortex-m7
FPU         = -mfpu=fpv5-d16
FLOAT_ABI   = -mfloat-abi=hard
C_DEFS      = -DUSE_HAL_DRIVER -DSTM32H743xx
LDSCRIPT    = stm32h743zi_flash.ld
ASM_SOURCES = startup_stm32h743xx.s
endif

#######################################
# Compiler / Tools
#######################################
PREFIX = arm-none-eabi-
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
CXX =$(GCC_PATH)/$(PREFIX)g++
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
CXX = $(PREFIX)g++
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

#######################################
# MCU + Flags
#######################################
MCU = $(CPU) -mthumb $(FPU) $(FLOAT_ABI)
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections
CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections
CXXFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections -fno-exceptions -fno-rtti -std=c++17

ifeq ($(DEBUG),1)
CFLAGS += -g -gdwarf-2
CXXFLAGS += -g -gdwarf-2
endif
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"
CXXFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# Sources
#######################################

# ThreadX sources
#THREADX_SRC = \
#$(wildcard Middlewares/azure-rtos/threadx/common/src/*.c) 


C_SOURCES = \
HAL/ST/stm32f4/Configs/stm32_hal_msp.c \
App/Src/sysmem.c \
APP/Src/syscalls.c \

C_SOURCES += $(THREADX_SRC)

ifeq ($(MCU_FAMILY),F4)
C_SOURCES += \
CMSIS/Vendor_Device/ST/STM32F4xx/Source/system_stm32f4xx.c \
$(wildcard HAL/ST/stm32f4/STM32F4xx_HAL_Driver/Src/*.c)
endif


CPP_SOURCES = \
App/Src/stm32f4xx_it.cpp \
App/Src/main.cpp \
HAL/ST/stm32f4/Configs/stm32_clock.cpp \
HAL/ST/stm32f4/Configs/stm32_hal_init.cpp \
HAL/ST/stm32f4/Stm32Uart.cpp \
HAL/ST/stm32f4/Stm32IO.cpp \
PAL/Board/HardwareInit.cpp \
PAL/PALWrappers/UartWrapper.cpp \
PAL/PALWrappers/Pin.cpp


#######################################
# Includes
#######################################
C_INCLUDES = \
-IApp/Inc \
-ICMSIS/Vendor_Device/ST/STM32F4xx/Include \
-ICMSIS/Core/Include \
-IHAL \
-IHAL/ST/stm32f4/Configs \
-IHAL/ST/stm32f4 \
-IPAL \
-IPAL/PALWrappers \
-IMiddlewares/azure-rtos/threadx/common/inc \
-IMiddlewares/azure-rtos/threadx/ports/cortex_m4/gnu/inc \


ifeq ($(MCU_FAMILY),F4)
C_INCLUDES += \
-IHAL/ST/stm32f4/STM32F4xx_HAL_Driver/Inc \
-IHAL/ST/stm32f4/STM32F4xx_HAL_Driver/Inc/Legacy \
-IHAL/ST/stm32f4/STM32F4xx_HAL_Driver 
endif



#######################################
# Linker
#######################################
LIBS = -lc -lm -lnosys
# ThreadX prebuilt library
LIBDIR = Middlewares/azure-rtos/Output/threadx.a
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) \
          -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

#######################################
# Build
#######################################
OBJECTS = $(patsubst %, $(BUILD_DIR)/%, $(C_SOURCES:.c=.o))
OBJECTS += $(patsubst %, $(BUILD_DIR)/%, $(CPP_SOURCES:.cpp=.o))
OBJECTS += $(patsubst %, $(BUILD_DIR)/%, $(ASM_SOURCES:.s=.o))
OBJECTS += $(patsubst %, $(BUILD_DIR)/%, $(ASMM_SOURCES:.S=.o))

vpath %.c $(sort $(dir $(C_SOURCES)))
vpath %.cpp $(sort $(dir $(CPP_SOURCES)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin

$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.cpp
	@mkdir -p $(dir $@)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.s
	@mkdir -p $(dir $@)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.S
	@mkdir -p $(dir $@)
	$(AS) -c $(CFLAGS) $< -o $@


$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CXX) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@
$(BUILD_DIR):
	mkdir $@

clean:
	-rm -fR $(BUILD_DIR)

-include $(OBJECTS:.o=.d)

$(info ===== Build Configuration =====)
$(info MCU_FAMILY = $(MCU_FAMILY))
$(info CPU        = $(CPU))
$(info FPU        = $(FPU))
$(info FLOAT-ABI  = $(FLOAT-ABI))
$(info C_DEFS     = $(C_DEFS))
$(info LDSCRIPT   = $(LDSCRIPT))
$(info ASM_SOURCES= $(ASM_SOURCES))
$(info ===============================)